---
- name: verify disks have been provided
  fail: msg="please provide osd disks"
  when: ceph.disks is not defined

- name: install dependencies
  apt: pkg={{ item }}
       state=present
  with_items: "{{ ceph.osd_pkgs }}"
  register: result
  until: result|succeeded
  retries: 5

- name: install bcache dependencies
  apt: pkg={{ item }}
       state=present
  with_items: "{{ ceph.bcache_pkgs }}"
  when: ceph.bcache_ssd_device is defined
  register: result
  until: result|succeeded
  retries: 5

- name: register admin.keyring
  slurp: src=/etc/ceph/ceph.client.admin.keyring
  register: admin_keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: write admin.keyring
  copy:
    dest: "{{ admin_keyring['source'] }}"
    content: "{{ admin_keyring['content'] | b64decode }}"

- name: register ceph.keyring
  slurp: src=/var/lib/ceph/bootstrap-osd/ceph.keyring
  register: ceph_keyring
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: write ceph.keyring
  copy:
    dest: "{{ ceph_keyring['source'] }}"
    content: "{{ ceph_keyring['content'] | b64decode }}"

- include: standard.yml
  when: ceph.bcache_ssd_device is not defined

- include: bcache.yml
  when: ceph.bcache_ssd_device is defined

- name: delete default 'rbd' pool
  command: ceph osd pool delete rbd rbd --yes-i-really-really-mean-it
  register: poolout
  changed_when: poolout.stdout | search('removed')
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- name: create openstack pool
  ceph_pool:
    pool_name: "{{ ceph.pool_name }}"
  register: pool_output
  run_once: true
  delegate_to: "{{ groups['ceph_monitors'][0] }}"

- include: system_tuning.yml
  tags: ceph-osd
