---
- name: get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: install pip
  shell: python /tmp/get-pip.py

- name: python dependencies
  package:
    name: "{{ item }}"
  with_items: " {{ common.python.system_packages }}"
  #register: result
  #until: result|succeeded
  #retries: 5

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i {{ openstack.pypi_mirror }}'
  when: ansible_distribution_version == "12.04" and openstack.pypi_mirror is defined  and ansible_distribution == 'Ubuntu'
  register: result
  until: result|succeeded
  retries: 5

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i {{ openstack.pypi_mirror }}'
  when: ansible_distribution_version != "12.04"
  register: result
  until: result|succeeded
  retries: 5

- name: root user pip config directory
  file: dest=/root/.pip state=directory

- name: pip config file
  template: src=etc/pip.conf dest=/root/.pip/pip.conf
  when: openstack.pypi_mirror is defined

- name: easyinstall config file
  template: src=etc/pydistutils.cfg dest=/root/.pydistutils.cfg
  when: openstack.easy_install_mirror is defined

- name: update pip
  pip: name=pip version={{ common.pip_version }}
       extra_args='-i {{ openstack.pypi_mirror }}'
  when: ansible_distribution_version == "12.04" and openstack.pypi_mirror is not defined
  register: result
  until: result|succeeded
  retries: 5

- name: uninstall python-setuptools
  package: name=python-setuptools state=absent
  when: common.setuptools_version != "system"
  register: result
  until: result|succeeded
  retries: 5

- name: install pip setuptools
  pip: name=setuptools version={{ common.setuptools_version }}
  when: common.setuptools_version != "system"
  register: result
  until: result|succeeded
  retries: 5

- name: pin alembic to 0.7.0
  pip: name=alembic version=0.7.0
  register: result
  until: result|succeeded
  retries: 5

- name: install additional python packages
  git: repo={{ item.repo }} dest=/opt/stack/{{ item.name }}
       version={{ item.rev }} accept_hostkey=True
  with_items: "{{ common.python_extra_packages }}"

- name: pip install eventlet
  pip: name=eventlet
  register: result
  until: result|succeeded
  retries: 5

- name: install drivers
  command: python setup.py install chdir=/opt/stack/{{ item.name }}
  with_items: "{{ common.python_extra_packages }}"

- name: install shade bits for ansible modules
  pip:
    name: "{{ item }}"
  with_items:
    - shade>=1.9.0
  register: result
  until: result|succeeded
  retries: 5
